package com.core.reactive.corereactive.util;

public class Offset {
    //    namespace CharacterIntermediate {
    //        static constexpr auto flatArmorPenetration = 0x3D8;
    //        static constexpr auto physicalLethality = 0x3F0;
    //        static constexpr auto percentArmorPenetration = 0x408;
    //        static constexpr auto percentBonusArmorPenetration = 0x420;
    //        static constexpr auto percentCritBonusArmorPenetration = 0x438;
    //        static constexpr auto percentCritTotalArmorPenetration = 0x450;
    //        static constexpr auto flatMagicPenetration = 0x468;
    //        static constexpr auto magicLethality = 0x480;
    //        static constexpr auto percentMagicPenetration = 0x498;
    //        static constexpr auto percentBonusMagicPenetration = 0x4B0;
    //    }
    //constexpr inline uintptr_t MissileManager = 0x21D3E78;				    //48 8B 0D ? ? ? ? 48 8D 54 24 ? E8 ? ? ? ? 48 8B 7C 24 ?
    //constexpr inline uintptr_t PingNet = 0x21B7370;							//48 8B 05 ? ? ? ? 4C 8B CA 48 8B D9
    //constexpr inline uintptr_t TurretList = 0x21C0C80;						//48 8B 1D ? ? ? ? 48 8B 5B 28
    //constexpr inline uintptr_t InhibList = 0x21D4078;							//48 8B 05 ? ? ? ? 48 89 7C 24 ? 48 8B 58 08
    //constexpr inline uintptr_t ChatClient = 0x21D3F18;						//48 8B 05 ? ? ? ? 88 90 ? ? ? ? C3
    //constexpr inline uintptr_t HudInstance = 0x21B7390;						//48 8B 0D ? ? ? ? 8B 57 10
    //constexpr inline uintptr_t ViewPort = 0x21BA340;							//48 8B 3D ? ? ? ? FF 90 ? ? ? ?
    public static final long localPlayer = 0x21D3D70; //48 8B 05 ? ? ? ? 4C 8B D2 4C 8B C1
    public static final long gameTime = 0x21C6E50; //F3 0F 5C 35 ? ? ? ? 0F 28 F8
    public static final long viewProjMatrix = 0x221C0E0; //48 8D 0D ? ? ? ? 0F 10 00
    public static final long championList = 0x21B74A0; //48 8B 05 ? ? ? ? 45 33 E4 0F 57 C0
    public static final long minionList = 0x21BA380; //48 8B 0D ? ? ? ? E8 ? ? ? ? E8 ? ? ? ? E8 ? ? ? ? 48 8B C8
    public static final long objIndex = 0x10;
    public static final long objName = 0x3868;
    public static final long objTeam = 0x3C;
    public static final long objLevel = 0x3FD0;
    public static final long objHealth = 0x1068;
    public static final long objMaxHealth = 0x1070;
    public static final long objArmor = 0x1694;
    public static final long objBonusArmor = 0x16A8;
    public static final long objArmorPen = 0x1590;
    public static final long objBaseAttack = 0x166C;
    public static final long objBonusAttack = 0x15D8;
    public static final long objLethality = 0x1598;
    public static final long objActionState = 0x13C0;
    public static final long objBonusAttackSpeed = 0x164C;
    public static final long objAttackSpeedMultiplier = 0x1668;
    public static final long objAbilityPower = 0x15E8;
    public static final long objAttackRange = 0x16C4;
    public static final long objSpawnCount = 0x338;
    public static final long objTargetable = 0xEC0;
    public static final long objVisible = 0x320;
    public static final long objPositionX = 0x220;
    public static final long objSpellBook = 0x30C8;
    public static final long spellInstanceClient = 0x38;
    public static final long spellCastInfo = 0x8;
    public static final long spellCastData = 0x0;
    public static final long spellCastSlotId = 0x8;
    public static final long spellCastEndTime = 0x164;
    public static final long spellCastStartTime = 0x180;
    public static final long spellCastStartPosition = 0xA4;
    public static final long spellCastEndPosition = 0xB0;
    public static final long spellCastWidth = 0x14C;
    public static final long spellCastDelay = 0xF0;
    public static final long spellCastIsBasicAttack = 0x113;
    public static final long spellCastNextAttackTime = 0x168;
    public static final long spellCastNetworkId = 0x94;
    public static final long aspellCastTargetArray = 0xE0;
    public static final long spellCastTargetArraySize = 0xE8;
    public static final long spellCastSourceId = 0x88;
    public static final long spellBookSlotLevel = 0x28;
    public static final long spellBookSpellTime = 0x30;
    public static final long spellBookSlotDamage = 0x90;
    public static final long aiManager = 0x3700;
    public static final long aiManagerMovementSpeed = 0x2B8;
    public static final long aiManagerIsMoving = 0x2BC;
    public static final long aiManagerPassedWaypoints = 0x2C0;
    public static final long aiManagerStartPath = 0x2D0;
    public static final long aiManagerEndPath = 0x2DC;
    public static final long aiManagerWaypoint = 0x14;
    public static final long aiManagerWaypointArray = 0x2E8;
    public static final long aiManagerWaypointCurrentSize = 0x2F0;
    public static final long aiManagerWaypointMaxSize = 0x2F4;
    public static final long aiManagerServerPosition = 0x414;
    public static final long aiManagerVelocity = 0x41C;
    public static final long aiManagerIsDashing = 0x324;
    public static final long aiManagerCurrentSegment = 0x1C4;
    public static final long aiManagerDashSpeed = 0x300;
    public static final long minimapObject = 0x21B8D98;
    public static final long minimapObjectHud = 0x320;
    public static final long minimapHudPos = 0x60;
    public static final long minimapHudSize = 0x68;
}
